### ISSUE TITLE
It doesn't have versioning

### ISSUE THREAD

**Issue by sinner** [litwicki/chargify-bundle#1]
This bundle doesn't have versioning and give conflicts with composer installations such as:

    1.- The requested package litwicki/chargify-bundle master is satisfiable by litwicki/chargify-bundle[dev-master] but these conflict with your requirements or minimum-stability.

Moreover this doesn't offer a stable branch.

**Comment by litwicki** [comment]
This is still very early development, so there isn't a "stable" release in the traditional sense yet. I'm just revisiting this now and plan to have one in the next few weeks, but for now you'll need to relax your minimum-stability to include `dev-master` to use this Bundle.
